http:
  host: "localhost"
  port: "8081"

sf:
  user: "sdunna@miraclesoft.com"
  
syncAccount: "true"

batch:
  block:
    size: "100"
  agg:
    size: "5"

database:
  dynamics:
    host: "172.17.35.52"
    port: "3306"
    user: "integration"
    database: "digital_integrations_db"
 
